name: Moosic
main: no.runsafe.moosic.Plugin
version: 1.0.@BUILD@
author: Kruithne
description: Customized music plug-in
commands:
  playsong:
    description: Plays a song at your location
    aliases: [ps, song]
  stopsong:
    description: Forces a song to stop
  makerecord:
    description: Turns the record being held into a custom one
